### ISSUE TITLE
Determine if we should just switch to Jekyll

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-web-and-design/landscape-docs#71]
That's what snapcraft switched to: https://github.com/canonical-docs/snappy-docs

**Comment by BryanQuigley** [comment]
I've never had much luck with Jekyll personally, but I've determined importing the pages really only requires a header to convert - my favorite nikola worked great:
nikola new_page -f markdown -i en/ReleaseNotes19.01.md 

I guess the real question is - is documentation-builder on the way out?  Thanks!

**Comment by nottrobin** [comment]
[documentation-builder](https://github.com/canonical-webteam/documentation-builder) is likely on the way out because [our recommended new model for human created documentation is to keep it in Discourse](https://canonical-webteam.github.io/practices/project-structure/documentation.html).

So, for https://docs.snapcraft.io the documentation content is all in topics on https://forum.snapcraft.io/c/doc, and the [website application](https://github.com/canonical-websites/docs.snapcraft.io) simply pulls the content from there. The [snappy-docs](https://github.com/canonical-docs/snappy-docs) repository is legacy at this point and should really just be archived.

docs.snapcraft.io is the only site using this model right now, but Juju and MAAS docs are moving over ASAP, followed by everything else. For documentation about products that don't warrant their own Discourse forum, we plan to keep that documentation in other Discourses - for example https://discourse.ubuntu.com.

So, much as I'm a fan of Jekyll sites in general, I don't think there's much point converting this or any documentation set from documentation-builder to Jekyll. They should just stay as they are for now until they can be moved into Discourse and retired.

I hope this answers your query so I'm going to close this for now. But reply if you think that's the wrong decision and we can re-open it.

**Comment by BryanQuigley** [comment]
We may eventually want to include some of these docs - preinstalled with Landscape On Prem.  (Some are today).   I think we'd prefer to not go the discourse route, and go directly to another markdown that can be trivially packaged in OnPrem for offline use.

**Comment by nottrobin** [comment]
We're going to have a generic solution for taking a snapshot of docs from Discourse for cases like this. E.g. we'll need something similar for MAAS. Downloading this documentation should be fairly trivial with a tool like https://github.com/howbazaar/discli/pull/2. So this needn't be an argument against moving docs to the Discourse model.

documentation-builder has already been deprecated and will be retired, and it's not currently our plan to support any other markdown-based documents through another model. If the documentation is hand-written, Discourse is our solution. The case where we'd expect to have a different solution is where documentation is generated through another means, e.g. from inline comments in code.
